server:
  port: 8761                                              # 端口
eureka:
  client:
    register-with-eureka: false                           # 是否注册自己
    fetch-registry: false                                 # 是否注册其他的euraka
    service-url:
      defaultZone: http://localhost:8761/eureka/         # 注册中心地址